const GENERAL = 'C1LQU6N3H';
const SPOTBOT_TESTING_GROUND = 'G01B20H3KK3';
const PM_ELI = 'U1LPCUSTV';

const CHANNELS = {
  birthday: SPOTBOT_TESTING_GROUND,
  channelSpotlight: SPOTBOT_TESTING_GROUND,
};

export default CHANNELS;
